// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQOmEQiPtGj7HIuaii0AT4vRB4mGKv4ms',
    appId: '1:746314154452:web:ffa8004cc9ba7c86999641',
    messagingSenderId: '746314154452',
    projectId: 'ccc-lock',
    authDomain: 'ccc-lock.firebaseapp.com',
    databaseURL: 'https://ccc-lock-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ccc-lock.appspot.com',
    measurementId: 'G-JBHXMGLKTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMT96RXdEDzF8cSeY4uwFJ-tK6KgwNtr4',
    appId: '1:746314154452:android:3162b07bcfdac402999641',
    messagingSenderId: '746314154452',
    projectId: 'ccc-lock',
    databaseURL: 'https://ccc-lock-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ccc-lock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARC9eo9MS0vUXaCqLREZVCmahM0j8pK0U',
    appId: '1:746314154452:ios:e8a400edfddce1ed999641',
    messagingSenderId: '746314154452',
    projectId: 'ccc-lock',
    databaseURL: 'https://ccc-lock-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ccc-lock.appspot.com',
    iosBundleId: 'com.example.ccc',
  );
}
